server:
  port: 8081
  context-path: /hello-groovy
  # 开启压缩
  compression:
    # 开启
    enabled: true
    # 执行压缩的阈值，默认为2048
    min-response-size: 1024
    # 指定要压缩的MIME type，多个以逗号分隔
    mime-types:
      - application/json
      - application/xml
      - text/xml
      - text/plain
spring:
  # profiles: dev
  datasource:
    # 个人服务器 的 数据库服务器
    url: jdbc:mysql://129.204.120.115:3306/mins?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: mins*#56
    #url: jdbc:mysql://192.168.97.180:3306/wjdbmgrapp?autoReconnect=true
    #username: mgrapp_all
    #password: mgrapp123!@#
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    initialize: true
    sql-script-encoding: UTF-8
  jmx:
    enabled: false
  data:
    mongodb:
      # uri配置
      # uri: mongodb://hellogro:hellogro!#$@129.204.120.115:27017/app
      host: 129.204.120.115
      port: 27017
      username: hellogro
      password: hellogro
      database: app
  redis:
    host: 129.204.120.115
    port: 6379
    database: 5
    pool:
      max-active: 12
      max-wait: 1000
      max-idle: 8
      min-idle: 0
    timeout: 5000
  #jpa:
    #hibernate:
      #ddl-auto: none
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

hibernate:
  hbm2ddl:
    auto: update
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.spring: WARN
  # path: /home/www/log/manager_app
  # path: ./logs